version: "3.1"
services:
  webserver: &webserver
    build: .
    container_name: mvc-webserver
    working_dir: /app
    depends_on:
      - mariadb
    volumes:
      - ./app:/app
    ports:
      - "80:80"
  mariadb:
    image: mariadb:10.4
    container_name: mvc-mariadb
    working_dir: /application
    volumes:
      - ./db:/application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mvc_crud
      - MYSQL_USER=mvc
      - MYSQL_PASSWORD=mvc
    ports:
      - "1028:3306"
  testing: &testing
    working_dir: /app
    volumes:
      - ./app:/app
    image: jakzal/phpqa:alpine
    container_name: mvc-testing
